<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	 <br> <br> <br> <br> <center> <a href="#barandales"> BARANDALES </a> &nbsp;&nbsp;&nbsp; <a href="#escaleras"> ESCALERAS </a> <br> <br> <br> <br> <br> <br> </center>
	  
	  <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="750">
		<center> <center> <a name="barandales"> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TU BARANDAL IDEAL! </i> </u> </b> </font> </center> <br>
		<i> La correcta elección del barandal, además de dejar la casa bonita, trae seguridad. <br> 
		El uso de este es importante a partir del desnivel de dos escalones, o de una inclinación de 40 centímetros.
        El barandal es una barra de superficie lisa y redondeada que acompaña a los lados de las escaleras y rampas, ayudando a 
		quien camina por ellas. Es un apoyo para el cuerpo, que aporta más equilibrio y seguridad.<br>
 		Este elemento de seguridad es utilizado principalmente por los niños, mujeres embarazadas, ancianos y portadores de necesidades especiales. <br> 
		Su instalación no siempre es obligatoria, pero su importancia es evidente. <br>
        Hay tres tipos de instalación. Estas pueden ser montadas en la pared,en el suelo o en los escalones.</i>
		</tr> </td> </table>  </center> <br> </div>
	  
	 <img src="imagenes\barandales.png"> <br> 
	 
	 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="950">
		<center> <center> <a name="escaleras"> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TU ESCALERA IDEAL! </i> </u> </b> </font> </center> <br>
		<i> Las escaleras interiores son un elemento clave para poder cambiarle la cara a una estancia y darle ese toque especial. <br>
		Por eso es fundamental saber escoger aquellas que te ayuden a conseguir ese resultado ideal que tienes en mente. <br>
		Para dar con el diseño de escaleras interiores perfecto la coherencia es la clave. <br> 
		¿A qué nos referimos? Piensa en el espacio del que dispones, en cómo es y en qué le falta. 
		Así podrás elegir las escaleras interiores que se adapten plenamente a tu casa. <br>
		Para encontrar unas escaleras interiores de lo más funcionales es esencial que te hagas estas preguntas antes de elegirlas:
		<ul type="1">
		 <li> ¿Que espacios van a conectar </li>
		 <li> ¿De cuanto espacio dispone? </li>
		 <li> ¿Con cuanta frecuencia se usa? </li>
		 <li> ¿Estaran visibles? </li> 
		 <li> ¿Edades de las personas que las usan? </li>
		</ul>
		Todo esto es importante porque si las vas a usar a diario, es imprescindible que elijas materiales robustos. <br>
		Si por el contrario serán para un uso más esporádico como acceder al altillo, las escaleras plegables serán las más funcionales. <br>
		En el caso de que haya niños, ancianos o personas con movilidad reducida en casa, la seguridad pesará más que la estética. <br>
		Si tu principal limitación es el espacio, será mejor que optes por escaleras interiores ahorra espacio como puedan ser las de caracol.
	   </tr> </td> </table>  </center> <br> </div>
	 
	 <img src="imagenes\escaleras.png">
	 
	 
	 </center>
   <?php
include("PIE_INCLUDE.HTML");

?>