<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
   
	 <br> <br>

      <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="750">
		<center> <center> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TUS BARRAS DE COCINA IDEALES! </i> </u> </b> </font> </center> <br>
		<i> Las barras de cocina o mesas de trabajo se ha convertido en una pieza importante de mobiliario en nuestro negocio, ya que se sitúa 
		como el principal elemento de apoyo y soporte. <br>
		A su vez no hay que olvidar que también es un espacio destinado al trabajo, y si hay un elemento que se utiliza a diario es la barra 
		de la cocina para cocinar y preparar el alimento, por lo que es imprescindible una buena elección. <br>
		El acero inoxidable es el material más resistente a los golpes y rayaduras, por lo que es la alternativa más favorable a la limpieza y mantenimiento.
	    Se podría afirmar, que una encimera de acero inoxidable es para siempre. Sus puntos fuertes son muchos; impermeable frente a las humedades, 
		gran dureza frente a golpes y resistencia a las altas temperaturas. </i>
		</tr> </td> </table>  </center> <br> </div>
		
		
	  <center> <img src="imagenes\barras.png"> </center>
	  
	 
   <?php
include("PIE_INCLUDE.HTML");

?>