  <?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
  <div align="center">    
		 <marquee direction="down" width="1250" height="90" behavior="alternate">
		   <marquee behavior="alternate">
 
 
	   <font face="stencil" size="6" color="silver"> <i> <b> <span style="background-color:black"> ¡ELABORAMOS SUS PROYECTOS EN BASE AL DISEÑO DE SU TOTAL ELECCIÓN! </span> </b> </i>  </font> 
	  </marquee> </marquee>  </div> 
	
	 <br><br>
	 <marquee direction="left" behavior="alternate">  <br /> <img height="400px" border="7" width="1000px" src="imagenes\soldando-1.png"/> </marquee> <br /> 
	 <marquee direction="right" behavior="alternate">  <br /> <img height="600px" border="7" width="1000px"  src="imagenes\soldando-16.png."/>   </marquee> <br />
    
     <br> 
	<center>  <audio src="audios/ambientacion-herreria.mp3" autoplay controls> </center>
	<center> <video src="videos/Particle tests krakatoa.mp4" width="1000" height="1000" autoplay></video> </center> 
 <br>  
 
 <?php
 include ("PIE_INCLUDE.HTML");
 ?>