<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	
	 <br> 
	 <center>
	<table border="3" bgcolor="silver" border color="627B56"> 
	 <tr> <td> <div align="left"> <font face="impact" size="4" color="black"> <b> COTIZACIONES </b> <br>
	 Para efectuar su cotización correspodiente, le agradeceríamos contactarnos mediante los siguientes medios: <br> <tr> </td>  
	 </div> </font>
	 <tr> <td> <center>  <a href="iniciosesion.php" TARGET="Contenido"> <img src="imagenes\llenar-formulario.png"> </a> </tr> </td> </center>
	 <tr> <td> <center> <img src="imagenes\what.png" width="40px" height="40px"> <font face="impact" size="5"> 55 59 64 15 10 </tr> </td> </center>
	 <tr> <td> <center> <img src="imagenes\telefono.png" width="40px" height="40px"> <font face="impact" size="5"> 55 - 59 - 64 - 15 - 10 </tr> <td> </center>
	 <tr> <td> <center> <img src="imagenes\correo.png" width="40px" height="40px"> <font face="impact" size="5"> <i> <b> <u> herreria.iw@gmail.com </i> </b> </u> </td> </tr> </center> </center> </table>
	 <br> <br> 
	
     <center>
     <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3762.8691043539447!2d-99.07018568580823!3d19.4180607868926!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1fc661c5f3cd3%3A0xe6a286d0449bab18!2sAgr%C3%ADcola%20Pantitl%C3%A1n%2C%2008100%20Ciudad%20de%20M%C3%A9xico%2C%20CDMX!5e0!3m2!1ses-419!2smx!4v1602105896666!5m2!1ses-419!2smx" 
     width="800" height="600" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
     </center> <br> <br>
  
	<table border="3" bgcolor="silver" border color="627B56">
	 <tr> <td> <div align="center"> <font face="impact" size="4"> Para agilizar su presupuesto indicarnos en el correo o mensaje las especificaciones de su 
	 proyecto así como una fotografía en caso de tenerla, esto con la finalidad de brindarle una cotización expedita. <br> <br> </div>
	 <center> <u> Para la realización de todo tipo de presupuesto, integramos en los costos de cada proyecto de manera analizada y con precisión los materiales y
	 volumetría real para brindar el mejor costo y servicio. <br> <br> </u> 
	 Su presupuesto le sera proporcionado en un tiempo máximo de 24 horas. 
	 <ul type="circle">
	  <li> Numero de cotización </li> 
	  <li> Precios unitarios </li> 
	  <li> Programa de instalación </li>
	 </ul>
	 
	 <i> !De esta forma podra evaluar nuestros presupuestos de forma objetiva, siempre en beneficio de su obra¡ </i> </tr> </td> 
	 
	 </center> </tr> </td> 
	 </font>
	 </table>
	  <div align="right"> <a href="referencias.html"> <img src="imagenes\siguiente-boton.png"> </a> </div>
	 
  <?php
include("PIE_INCLUDE.HTML");

?>