<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	 
	 <center>	
	 <a href="cubiertas.php"> <img src="imagenes\boton-cubiertas.png"> </a>
	 <a href="marquesinas.php"> <img src="imagenes\boton-marquesinas.png"> </a>
	  <br> <br> </center>
	  
	   <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="850">
		 <center> <b> <i> <u> !ELIJE TU CUBIERTA IDEAL! </b> </i> </u> </center> <br>
        <i> <center> Las cubiertas metálicas son la parte más delicada en toda construcción de nave industrial, el diseño  exige fiabilidad y durabilidad, 
		ya que de lo contrario se corre el riesgo de tener goteras, que el techo se venza, entre otros. <br>
		Se le llama cubierta al sistema de cierre en la parte superior y exterior de una construcción, un edificio, losa de azotea; 
		aquella parte exterior de la techumbre de un edificio, también puede hacer referencia a la estructura que la sustenta. </i>
		</tr> </td> </table>  </center> <br> </div>
		
		 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="450">
		 <center> <b> <i> <u> BENEFICIOS </b> </i> </u> </center> <br>
        <i> <center> <ul type="circle">
		 <li> Nuevos espacios a corto plazo </li>
		 <li> Permiten el paso de la luz, ayudan así el ahorro de energía eléctrica. </li>
		 <li> Montaje rápido y flexibilidad de uso </li>
		 <li> Alta calidad </li>
		 <li>  Volúmenes adecuados y variables. </li> 		 
		</ul>
		
		 <center> <b> <i> <u> TIPOS DE CUBIERTAS </b> </i> </u> </center> <br>
        <i> <center> <ul type="circle">
		 <li> PLANA </li>
		 <li> INCLINADA </li>
		 <li> BOVEDA </li>	 	 
		</ul>
		</tr> </td> </table>  </center> <br> </div>
	
	 
	  
	<img src="imagenes\cubiertas.png">
	<img src="imagenes\cubiertas-2.png">
	</center> 
   
	<?php
include("PIE_INCLUDE.HTML");

?>