<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	 
	<br>
	
	<center>	
	 <a href="cubiertas.php"> <img src="imagenes\boton-cubiertas.png"> </a>
	 <a href="marquesinas.php"> <img src="imagenes\boton-marquesinas.png"> </a>
	  <br> <br> </center>
	  
	 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="850">
		 <center> <b> <i> <u> "FUNCIONALES Y RESISTENTES" </b> </i> </u> </center> <br>
        <i> <center> Por estructura metálica se entiende cualquier estructura cuyas partes son en su mayoría materiales metálicos. <br>
		Las estructuras metálicas son utilizadas habitualmente en el sector industrial debido a que aportan excelentes características para la construcción. <br>
        Una estructura, por definición, es un conjunto de partes unidas entre si que forman un cuerpo, una forma o un todo, cuyo fin es el de soportar los 
		efectos de las fuerzas que actúan sobre el cuerpo.  </i>
		</tr> </td> </table>  </center> <br>
	
	
	<center> <font face="impact" size="4" color="black"> <span style="background-color:DADBD9"> <u> Seleccione el articulo de su interes en el siguiente cuadro. <u> </font> </span> <br> <br> </center>
	 
	 <center> <img src="imagenes\menu-estructuras.png" usemap="#menuestru"> 
	 <map name="menuestru">
	     <area shape="rect" coords="112,98,337,315" href="cubiertas.php">
		 <area shape="poly" coords="550,80,658,168,617,309,488,311,445,165" href="marquesinas.php">
	 </map> <br>
	  
	 <?php
       include("PIE_INCLUDE.HTML");

     ?>