 <?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
   <br> <br> <br>   
   <center>
   <table border='7' cellspacing=20>
   <tr bgcolor="#C5C4C4"> 
   <tr bgcolor="#C5C4C4"> <th><a name="inicio"> <a href="#descripción"> <b> IR A DESCRIPCION DEL OFICIO </b> </a> </th> </tr>
   <tr bgcolor="#C5C4C4"> <th><a href="#historía"> <b> IR A HISTORIA </b>  </a> </th> </tr>
   <tr bgcolor="#C5C4C4"> <th><a href="#arqui"> <b> IR A ARQUITECTURA Y CONSTRUCCION </b> </a>  </th> </tr>
   <tr bgcolor="#C5C4C4"> <th><a href="#producto"> <b> ELEGIR PRODUCTO </b> </a> <br>  </th> </tr>
   </tr>
   </table>   </center>
   <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 
	 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="550"> <center> <a name="descripción"> <b> <u> <font face="constantia"> <b> &iquest;Que es la herrer&iacute;a? </b> </u> </i> </center> <br> 
		<p align="justify"> <i> La herrer&iacute;a es el oficio de labrar el hierro. Generalmente el metal es calentado hasta que se vuelve incandescente, 
		lo que solemos llamar al rojo vivo y posteriormente se somete al proceso de forjado. </p>
		Las manufacturas t&iacute;picas de la herrer&iacute;a son elementos de hierro forjado, rejas, muebles, esculturas, herramientas, 
		art&iacute;culos decorativos y religiosos, campanas, utensilios de cocina y armas.</p> <p align="justify"> Un herrero con suficiente experiencia y 
		capacidad puede realizar con el m&iacute;nimo de esfuerzo y energ&iacute;a, productos de aspecto refinado que combinan talento y originalidad. </p> 
		<p align="justify"> La herrer&iacute;a es una de las pocas disciplinas en las cuales sus artesanos pueden jactarse de confeccionar ellos mismos sus propias herramientas. </P>
		<br> <center> <a href="#inicio"> Ir a inicio </a> </center> <br> <br> </b> <i> </font> </tr> </td> </table> </div>
		<br> <br> <br>
		<center> <img src="imagenes\definicion.jpg" width="950" height="550"> </center>
		<br> <br> <br> 
		<hr size="9" width="80%">
		
	 <br> <br> <br> <br> <br> <br> <br> <br> 
	 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="550">
		 <center> <a name="historía"> <i> <b> <u> <font face="constantia"> <b> Historia de la herrer&iacute;a </u>  </i> </center> <br>
        <p align="justify"> <i> Mucho antes de la Revoluci&oacute;n industrial, el herrero de la aldea era un vecino b&aacute;sico de cualquier poblado.</p>  
		<p align="justify">Las t&eacute;cnicas de producci&oacute;n en masa han reducido la demanda de la herrer&iacute;a m&aacute;s tradicional 
		con excepci&oacute;n de &Aacute;frica, India, y el Sudeste asi&aacute;tico, lugares en donde a&uacute;n se mantienen estos herreros tradicionales. </p>
		<p align="justify"> En la mitolog&iacute;a la herrer&iacute;a estaba representada por el dios griego Hefesto  (Vulcano para los romanos), quien fue 
		el herrero de las deidades. Hefesto era un artesano con habilidades &uacute;nicas cuya fragua era un volc&aacute;n y fue&eacute;l quien construy&oacute; 
		la mayor&iacute;a de las armas de los dioses.  Se le consideraba el dios de la herrer&iacute;a, la artesan&iacute;a, la escultura, la metalurg&iacute;a 
		y el fuego. <p>
		<p align="justify"> En la antig&uuml;edad, los herreros eran respetad&iacute;simos artesanos, indispensables para el transporte, por su trabajo con los 
		caballos, para la guerra y para la vida en general. La herrer&iacute;a era uno de los principales factores de la econom&iacute;a local de los tiempos 
		anteriores a la revoluci&oacute;n industrial. Incluso hoy en d&iacute;a, la herrer&iacute;a es muy usada en la arquitectura, el dise&ntilde;o 
		de interiores y de exteriores y la decoraci&oacute;n. <p>
		<p align="justify"> La herrer&iacute;a era indispensable para la fabricaci&oacute;n de armas y de las herramientas necesarias para crearlas, 
		as&iacute; que los aspectos b&eacute;licos necesitaban tanto de los herreros como de los generales. </p>
		<br> <center> <a href="#inicio"> Ir a inicio </a> </b> </i> </center> <br> <br> </tr> </td> </table>  </center>  
		<br> <br> <br>
		<center> <img src="imagenes\historia.jpg" width="950" height="550"> </center>
		<br> <br> <br> 
		<hr size="9" width="80%">
		
		<br> <br> <br> <br> <br> <br> <br> <br> 
		 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="550">
		 <center> <a name="arqui"> <b> <i> <u> <font face="constantia"> La arquitectura y La construcci&oacute;an </b> </i> </u> </center> <br>

        <i> <b> <p align="justify"> La herrer&iacute;a es una disciplina absolutamente indispensable para la construcci&oacute;an de la infraestructura de una ciudad,
		ya que se crean piezas como varillas, vigas y l&aacute;aminas, que son esenciales para poder terminar un proyecto. </p>
		<p align="justify"> Tambi&eacute;n se utiliza en las decoraciones, en rejas, muebles y esculturas, las cuales le dan un toque &uacute;nico al lugar en 
		donde se encuentren. </p>
		<p align="justify"> Se crean tambi&eacute;n piezas para la cocina, muchos de los art&iacute;culos  est&aacute;an creados por herreros, todo esto son cosas que las 
		familias en distintas partes del mundo utilizan diario. </p>
		<p align="justify"> Con el hierro se pueden crear una gran variedad de objetos; muebles, rejas, escaleras, ventanas, esculturas, art&iacute;culos religiosos 
		y decorativos, al igual que utensilios de uso d&iacute;aario dentro de la cocina como; cazuelas, sartenes, ollas y cucharones. </p>
		<p align="justify"> Tambi&eacute;an se crean materiales de uso com&uacute;an e insustituible en las 
		construcciones como varillas, vigas, tuercas y laminas que sirven para dar soporte a la cimentaci&oacute;an. </p> </i>
		<br> <center> <a href="#inicio"> Ir a inicio </a> </b> </center> <br> <br> </tr> </td> </table> </font>  </center> <br> <br> 
		<br> <br> <br>
		<center> <img src="imagenes\arqui.jpg" width="950" height="550"> </center>
		<br> <br> <br> 
		<hr size="9" width="80%">
		<br> <br> <br> <br> <br> <br> <br> <br> <br>
		<center>
	  <font face="impact" size="4" color="black"> <span style="background-color:DADBD9"> <a name="producto"> <u> Seleccione el art&iacute;culo de su inter&eacute;s en el siguiente cuadro. <u> </font> </span> <br> <br>
	
	  <img src="imagenes\collage-publi.jpg" usemap="#menu">
	   <map name="menu">
	     <area shape="poly" coords="80,53,155,26,235,56,233,106,155,136,79,106" href="protecciones.php">
		 <area shape="poly" coords="290,48,363,36,434,51,432,95,365,120,292,97" href="rejas.php">
		 <area shape="rect" coords="154,180,20,310" href="puertas y portones.php">
		 <area shape="circle" coords="255,255,85" href="barandales y escaleras.php">
		 <area shape="rect" coords="461,167,352,280" href="barras.php">
		 <area shape="poly" coords="31,377,128,349,220,376,223,442,127,468,30,439" href="cubiertas.php">
		 <area shape="poly" coords="290,394,375,372,463,396,463,445,376,467,290,443" href="marquesinas.php">
		</map> 
		<br> <center> <a href="#inicio"> <b>  Ir a inicio </b> </a> </center> <br> <br>
	
	</center>
 <?php
include("PIE_INCLUDE.HTML");

?>