<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
   
	 <br> <center>
	 <a href="cubiertas.php"> <img src="imagenes\boton-cubiertas.png"> </a>
	 <a href="maquesinas.php"> <img src="imagenes\boton-marquesinas.png"> </a>
    </center> <br> <br>
	
	<div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="850">
		 <center> <b> <i> <u> !ELIJE TU MARQUESINA IDEAL! </b> </i> </u> </center> <br>
        <i> <center> Las marquesinas son ideales para lugares de paso o estancias de personas como : hoteles, aeropuertos, campos de
                     futbol, clubs sociales, edificios, estacionamientos, entrada de viviendas, supermercados, etc...
                     Las marquesinas son construidas a medida según necesidades cliente, empleando pilares de perfiles rectangulares o
                     circulares, de hierro, acero inoxidable, aluminio, etc... Con diferentes acabados de remate y anclajes, cubiertas
                     en formas curvadas, con pendiente a una o varia aguas. </i>
		</tr> </td> </table>  </center> <br> 
	
	<center> <img src="imagenes\marqueisnas.png"> </center>
	
	<?php
include("PIE_INCLUDE.HTML");

?>