<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	 
	  
	   <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="750">
		<center> <center> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TUS PROTECCIONES IDEALES! </i> </u> </b> </font> </center> <br>
		<i> Sabemos que cuando acabas de adquirir una propiedad lo primordial es la seguridad de tu familia y pertenencias. Los protectores de ventanas 
		en herrería, además de proteger nuestro hogar, son un excelente recursos de decorado para nuestras fachadas e interiores. 
		Una ventana de herrería puede cambiar por completo la vista de nuestra casa.
        La herrería para ventanas no se queda atrás en cuanto a las tendencias en decoración de interiores y gustos. 
		Generalmente son de acero, hierro u otro metal, ya que por su función requieren de la más alta resistencia posible. 
		También son materia para dar rienda suelta a la creatividad de los diseñadores y crear diseños exclusivos y originales. </i>
		</tr> </td> </table>  </center> <br>

	  
	  <center>
	 <img src="imagenes/protecciones-ventanas.png">
	</center> <center>
	 
	<?php
include("PIE_INCLUDE.HTML");

?>