 <?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	 
	 <br> <br>
	
	<div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="750">
		<center> <center> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TU PORTON O PUERTA IDEAL! </i> </u> </b> </font> </center>
		 <i> Es importante que sepas, que debes focalizar lo que te conviene. Si, es verdad que hay gran variedad de modelos de portones. <br>
		Pero está claro que tendrás solo uno en tu casa. Y debes tomar en cuenta varios factores, 
		que es importante que consideres porque influyen en la estética, en lo funcional y sobre todo en la duración de tu inversión. </i>
		</tr> </td> </table>  </center> <br> 
		
	<div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="1000"> <center> 
		 <i> Un portón se convierte en una necesidad a partir del servicio que nos brinda, seguridad, protección y diseño a nuestra fachada.
        Los portones de herrería, también son conocidos como zaguanes de herrería o puertas de herrería para garage. <br>
		Estos tienen una larga historia que se resume en ayudar a limitar una propiedad brindando resguardo a la misma y seguridad a las personas 
		que la habitan. <br>
        Desde un tiempo a la fecha, además se ha convertido en un elemento de diseño para la construcción. 
		Los portones modernos pueden hacer que una fachada se remodele por completo. 
		Puede cambiar la apariencia de una fachada radicalmente, que luzca como nueva o puede terminar por arruinarla.
        Los portones para casas normalmente se recomiendan fabricarlos de metal. 
		La durabilidad y la resistencia que presentan respecto a portones de aluminio o portones de madera es mejor. 
		Nos enfocaremos entonces a los portones de herrería que son precisamente metálicos. </i> <br> </center>
		</tr> </td> </table>  </center> <br> 
		
		<center>
	  <img src="imagenes\puertas.png">
	  <img src="imagenes\puertas-2p.png">
	  <img src="imagenes\puertas-portones.png">
	 </center>
	 
	   
<?php
include("PIE_INCLUDE.HTML");
?>