<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
	   <center> <table border="3" bgcolor="silver" border color="627B56"> 
	     <tr> <th width="150">  <center> <font face="impact" size="4" color="black"> <u> 
		 FUENTES:  </th> </tr> </table>
		 <table border="3" bgcolor="silver" border color="627B56">
		 <tr> <td width="320" height="200"> IMAGENES: <u> <i> pinrest.com, inoximuebles.com, herreriaforja.com.mx, </u> </i> </td>
		 <td width="320"> AUDIO: <i> Trance 009 sound system- dreamscape </i> </td>
		 <td width="320"> VIDEO: <i> Particle tests - krakatoa </i>  </td>
		 <td width="600" height="200"> TEXTO: <u> <i> nexometal.com, cerrajeríavazquez.com, homify.com, cerrajeroseconomicoszaragoza.es, hierroonline.com </u> </i> </tr> </td> </font> </table>
       </center> </center>

       <div align="left"> <a href="Cotice.html"> <img src="imagenes/anterior-boton.png"> </a>
	   
 <?php
include("PIE_INCLUDE.HTML");

?>