<?php
include("ENCABEZADO_INCLUDE.HTML");
include ("MENU_INCLUDE.HTML");
?>
   
	 <br> <br> 
	 
	 <div align="center"> <table border="3" bgcolor="silver" border color="627B56">  
		<tr> <td width="750">
		<center> <center> <i> <u> <b> <font size="5" color="black"> ¡ELIGE TU REJA IDEAL! </i> </u> </b> </font> </center> <br>
		<i> Las rejas son elementos que nos brindan un poco más de seguridad en nuestras casas o apartamentos, 
		sobre todo si se vive en planta baja. Aunque éstas se utilizan por seguridad, se deben elegir las que vayan con 
		el estilo del hogar y sobre todas las cosas, que sean útiles y seguras. </i> </tr> </td> </table>  </center> <br> </div>
		
	 
	  <center> <img src="imagenes\rejas.png"> </center>
	    
   <?php
include("PIE_INCLUDE.HTML");

?>