
   <?php
     include("ENCABEZADO_INCLUDE.HTML");
     include ("MENU_INCLUDE.HTML");
    ?>
	 
	 <div align="center">
	  <marquee direction="down" width="510" height="90" behavior="alternate">
  <marquee behavior="alternate">
	   <font face="stencil" size="6" color="DADBD9"> <i> <b> ¿Quienes somos? </b> </i>  </font> 
	  </marquee> </marquee>
	   <font face="impact" size="4" color="ECE9EF"> 
	    <center>
		 <table border="3" bgcolor="silver" border color="627B56">
          <tr> <td> <center> Somos una empresa Mexicana con 8 años de experiencia, dedicada a la elaboracíon e instalación
		  de productos de herrería y estructuras metalicas. <br><br>
		   Contamos con una amplia variedad de diseños en acabados de herrería como son puertas, portones, 
		  ventanas, escaleras, barandales, rejas, domos, protecciones y mas, que te brindaran la oportunidad 
		  de elegir ese estilo unico que siempre has querido para tu hogar o negocio. </center>
		  <br><br> <b> <i> <font face="impact" size="6"> <center> !Ofrecemos diversas soluciones para todo lo relacionado con la seguridad de tu hogar o negocio¡ </b> </i> <br><br> </center> </font>
		  </tr> </td>
		  </center>
         </table>  
		 
		  <marquee direction="down" width="510" height="90" behavior="alternate">
  <marquee behavior="alternate">
	   <font face="stencil" size="6" color="DADBD9"> <i> <b> FILOSOFÍA </b> </i>  </font> </marquee> </marquee>
		  <center>
		 <table border="3" bgcolor="silver" border color="627B56"> 
		 <tr> <td> <center> Tenemos como finalidad encaminar nuestros obejetivos hacia la plena satisfacción de nuestros 
		  clientes, totalmente comprometidos en brindar excelente calidad en la elaboración de nuestros 
		  productos y siempre ir en busca de la mejora continua tanto en nuestra estrategía de negocio como 
          en nuestros procedimientos operativos. <br> <br>
		  Mantenemos la convicción de aceptar la diversidad de opiniones de nuestros clientes así como de nuestro
		  equipo de trabajo. <br> 
		  Para nosotros es fundamental la confianza que depositan nuestros clientes en cada proyecto que brindamos, 
          es nuestro deber respetarla.
		  Estamos comprometidos a entregar en tiempo y forma los productos elaborados. Nuestro equipo de trabajo le 
          ofrece la más calida atención y cordialidad a nuestros clientes. </center> <br> <br>
		  </tr> </td>
		  </table>
		  </center>
		   </font> 
		  <center> <img src="imagenes\soldando-7.png"> </center>
		   
		<?php
          include("PIE_INCLUDE.HTML");

         ?>
          		  

		  
		  
	  
	  
	   
	   
   
 